apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: opt-it-catalog
  description: Opt IT Backstage Template Catalog
spec:
  targets:
    - ./templates/aws-infrastructure/template.yaml
    - ./templates/azure-infrastructure/template.yaml
    - ./templates/gcp-infrastructure/template.yaml
    - ./templates/cicd-pipeline/template.yaml
    - ./templates/observability-stack/template.yaml
