# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Azure Infrastructure
# Generated by Opt IT Backstage
# DO NOT EDIT MANUALLY
# ================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  # Uncomment to configure remote state:
  # backend "azurerm" {
  #   resource_group_name  = "tfstate-rg"
  #   storage_account_name = "tfstate${{ values.client_name | replace('-', '') }}"
  #   container_name       = "tfstate"
  #   key                  = "${{ values.client_name }}-${{ values.environment }}.tfstate"
  # }
}

# ────────────────────────────────────────────────────────────────
# RESOURCE GROUP — always provisioned
# ────────────────────────────────────────────────────────────────

module "resource_group" {
  source = "./modules/resource-group"

  client_name           = var.client_name
  environment           = var.environment
  module_version        = "1.0.0"
  location              = var.location
  subscription_id       = var.subscription_id
  resource_group_suffix = "${{ values.resource_group_suffix }}"
}

# ────────────────────────────────────────────────────────────────
# VNET
# ${% if values.provision_vnet %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_vnet %}
module "vnet" {
  source = "./modules/vnet"

  client_name             = var.client_name
  environment             = var.environment
  module_version          = "1.0.0"
  location                = module.resource_group.location
  subscription_id         = var.subscription_id
  resource_group_name     = module.resource_group.resource_group_name
  vnet_address_space      = [var.vnet_address_space]
  public_subnet_prefixes  = split(",", var.public_subnet_prefixes)
  private_subnet_prefixes = split(",", var.private_subnet_prefixes)
  enable_nat_gateway      = ${{ values.enable_nat_gateway }}
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# NSG
# ${% if values.provision_nsg %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_nsg %}
module "nsg" {
  source = "./modules/nsg"

  client_name                   = var.client_name
  environment                   = var.environment
  module_version                = "1.0.0"
  location                      = module.resource_group.location
  subscription_id               = var.subscription_id
  resource_group_name           = module.resource_group.resource_group_name
  public_subnet_ids             = module.vnet.public_subnet_ids
  private_subnet_ids            = module.vnet.private_subnet_ids
  allowed_ssh_source_prefixes   = var.allowed_ssh_source != "" ? split(",", var.allowed_ssh_source) : []
  db_port                       = var.db_port
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# VM
# ${% if values.provision_vm %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_vm %}
module "vm" {
  source = "./modules/vm"

  client_name         = var.client_name
  environment         = var.environment
  module_version      = "1.0.0"
  location            = module.resource_group.location
  subscription_id     = var.subscription_id
  resource_group_name = module.resource_group.resource_group_name
  subnet_id           = module.vnet.private_subnet_ids[0]
  vm_size             = var.vm_size
  admin_username      = var.admin_username
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# BLOB STORAGE
# ${% if values.provision_blob %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_blob %}
module "blob_storage" {
  source = "./modules/blob-storage"

  client_name              = var.client_name
  environment              = var.environment
  module_version           = "1.0.0"
  location                 = module.resource_group.location
  subscription_id          = var.subscription_id
  resource_group_name      = module.resource_group.resource_group_name
  storage_suffix           = var.storage_suffix
  account_replication_type = var.replication_type
  container_names          = split(",", var.container_names)
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# SQL FLEXIBLE SERVER
# ${% if values.provision_sql %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_sql %}
resource "azurerm_private_dns_zone" "sql" {
  name                = "${{ values.client_name }}-${{ values.environment }}.${var.db_engine == "postgres" ? "postgres" : "mysql"}.database.azure.com"
  resource_group_name = module.resource_group.resource_group_name
}

resource "azurerm_private_dns_zone_virtual_network_link" "sql" {
  name                  = "${{ values.client_name }}-vnet-link"
  private_dns_zone_name = azurerm_private_dns_zone.sql.name
  resource_group_name   = module.resource_group.resource_group_name
  virtual_network_id    = module.vnet.vnet_id
}

module "sql" {
  source = "./modules/sql-flexible"

  client_name            = var.client_name
  environment            = var.environment
  module_version         = "1.0.0"
  location               = module.resource_group.location
  subscription_id        = var.subscription_id
  resource_group_name    = module.resource_group.resource_group_name
  delegated_subnet_id    = module.vnet.private_subnet_ids[1]
  private_dns_zone_id    = azurerm_private_dns_zone.sql.id
  db_engine              = var.db_engine
  db_version             = var.db_version
  sku_name               = var.sku_name
  admin_username         = var.admin_username
  admin_password         = var.admin_password
  high_availability_mode = var.ha_mode
}
${% endif %}
