# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Outputs
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

output "resource_group_name" {
  description = "Resource group name"
  value       = module.resource_group.resource_group_name
}

output "location" {
  description = "Azure location"
  value       = module.resource_group.location
}

${% if values.provision_vnet %}
output "vnet_id" {
  description = "VNet ID"
  value       = module.vnet.vnet_id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = module.vnet.private_subnet_ids
}
${% endif %}

${% if values.provision_vm %}
output "vm_private_ip" {
  description = "VM private IP address"
  value       = module.vm.private_ip_address
}
${% endif %}

${% if values.provision_blob %}
output "storage_account_name" {
  description = "Storage account name"
  value       = module.blob_storage.storage_account_name
}
${% endif %}

${% if values.provision_sql %}
output "sql_server_fqdn" {
  description = "SQL server FQDN — use as host in connection strings"
  value       = module.sql.server_fqdn
  sensitive   = true
}
${% endif %}
