# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Variables
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

variable "client_name" {
  type    = string
  default = "${{ values.client_name }}"
}

variable "environment" {
  type    = string
  default = "${{ values.environment }}"
}

variable "location" {
  type    = string
  default = "${{ values.location }}"
}

variable "subscription_id" {
  type      = string
  sensitive = true
  # Set via: export TF_VAR_subscription_id=$ARM_SUBSCRIPTION_ID
}

${% if values.provision_vnet %}
variable "vnet_address_space" {
  type    = string
  default = "${{ values.vnet_address_space }}"
}

variable "public_subnet_prefixes" {
  type    = string
  default = "${{ values.public_subnet_prefixes }}"
}

variable "private_subnet_prefixes" {
  type    = string
  default = "${{ values.private_subnet_prefixes }}"
}
${% endif %}

${% if values.provision_nsg %}
variable "allowed_ssh_source" {
  type    = string
  default = "${{ values.allowed_ssh_source }}"
}

variable "db_port" {
  type    = number
  default = ${{ values.db_port }}
}
${% endif %}

${% if values.provision_vm %}
variable "vm_size" {
  type    = string
  default = "${{ values.vm_size }}"
}

variable "admin_username" {
  type    = string
  default = "${{ values.admin_username }}"
}
${% endif %}

${% if values.provision_blob %}
variable "storage_suffix" {
  type    = string
  default = "${{ values.storage_suffix }}"
}

variable "replication_type" {
  type    = string
  default = "${{ values.replication_type }}"
}

variable "container_names" {
  type    = string
  default = "${{ values.container_names }}"
}
${% endif %}

${% if values.provision_sql %}
variable "db_engine" {
  type    = string
  default = "${{ values.db_engine }}"
}

variable "db_version" {
  type    = string
  default = "${{ values.db_version }}"
}

variable "sku_name" {
  type    = string
  default = "${{ values.sku_name }}"
}

variable "ha_mode" {
  type    = string
  default = "${{ values.ha_mode }}"
}

variable "admin_password" {
  type      = string
  sensitive = true
  # Set via: export TF_VAR_admin_password="your-password"
}
${% endif %}
