# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — GCP Infrastructure
# Generated by Opt IT Backstage
# DO NOT EDIT MANUALLY
# ================================================================

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }

  # Uncomment to configure remote state:
  # backend "gcs" {
  #   bucket = "${{ values.client_name }}-${{ values.environment }}-tfstate"
  #   prefix = "terraform/state"
  # }
}

# ────────────────────────────────────────────────────────────────
# VPC — always provisioned (GCP networking foundation)
# ────────────────────────────────────────────────────────────────

module "vpc" {
  source = "./modules/vpc"

  client_name         = var.client_name
  environment         = var.environment
  module_version      = "1.0.0"
  project_id          = var.project_id
  region              = var.region
  public_subnet_cidr  = var.public_subnet_cidr
  private_subnet_cidr = var.private_subnet_cidr
  enable_cloud_nat    = ${{ values.enable_cloud_nat }}
}

# ────────────────────────────────────────────────────────────────
# FIREWALL
# ${% if values.provision_firewall %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_firewall %}
module "firewall" {
  source     = "./modules/firewall"

  client_name               = var.client_name
  environment               = var.environment
  module_version            = "1.0.0"
  project_id                = var.project_id
  vpc_name                  = module.vpc.vpc_name
  allowed_ssh_source_ranges = var.allowed_ssh_ranges != "" ? split(",", var.allowed_ssh_ranges) : []
  db_port                   = var.db_port
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# COMPUTE ENGINE
# ${% if values.provision_gce %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_gce %}
module "gce" {
  source = "./modules/gce"

  client_name          = var.client_name
  environment          = var.environment
  module_version       = "1.0.0"
  project_id           = var.project_id
  region               = var.region
  zone                 = var.zone
  subnetwork_self_link = module.vpc.private_subnet_self_link
  machine_type         = var.machine_type
  boot_disk_type       = var.boot_disk_type
  network_tags         = [module.firewall.web_server_tag, module.firewall.ssh_access_tag]
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# CLOUD STORAGE
# ${% if values.provision_gcs %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_gcs %}
module "gcs" {
  source = "./modules/gcs"

  client_name       = var.client_name
  environment       = var.environment
  module_version    = "1.0.0"
  project_id        = var.project_id
  bucket_suffix     = var.bucket_suffix
  storage_class     = var.storage_class
  enable_versioning = ${{ values.enable_versioning }}
}
${% endif %}

# ────────────────────────────────────────────────────────────────
# CLOUD SQL
# ${% if values.provision_cloud_sql %}Provisioned${% else %}Not selected${% endif %}
# ────────────────────────────────────────────────────────────────

${% if values.provision_cloud_sql %}
module "cloud_sql" {
  source = "./modules/cloud-sql"

  client_name       = var.client_name
  environment       = var.environment
  module_version    = "1.0.0"
  project_id        = var.project_id
  region            = var.region
  vpc_self_link     = module.vpc.vpc_self_link
  db_engine         = var.db_engine
  db_version        = var.db_version
  tier              = var.tier
  availability_type = var.availability_type
  admin_password    = var.admin_password
}
${% endif %}
