# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Outputs
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

output "vpc_name" {
  description = "VPC network name"
  value       = module.vpc.vpc_name
}

${% if values.provision_gce %}
output "gce_internal_ip" {
  description = "GCE instance internal IP"
  value       = module.gce.internal_ip
}
${% endif %}

${% if values.provision_gcs %}
output "gcs_bucket_url" {
  description = "GCS bucket URL"
  value       = module.gcs.bucket_url
}
${% endif %}

${% if values.provision_cloud_sql %}
output "cloud_sql_connection_name" {
  description = "Cloud SQL connection name for Auth Proxy"
  value       = module.cloud_sql.connection_name
  sensitive   = true
}
${% endif %}
