# ================================================================
# ${{ values.client_name }} — ${{ values.environment }} — Variables
# Generated by Opt IT Backstage — DO NOT EDIT MANUALLY
# ================================================================

variable "client_name" {
  type    = string
  default = "${{ values.client_name }}"
}

variable "environment" {
  type    = string
  default = "${{ values.environment }}"
}

variable "project_id" {
  type    = string
  default = "${{ values.project_id }}"
}

variable "region" {
  type    = string
  default = "${{ values.region }}"
}

variable "zone" {
  type    = string
  default = "${{ values.zone }}"
}

variable "public_subnet_cidr" {
  type    = string
  default = "${{ values.public_subnet_cidr }}"
}

variable "private_subnet_cidr" {
  type    = string
  default = "${{ values.private_subnet_cidr }}"
}

${% if values.provision_firewall %}
variable "allowed_ssh_ranges" {
  type    = string
  default = "${{ values.allowed_ssh_ranges }}"
}

variable "db_port" {
  type    = number
  default = ${{ values.db_port }}
}
${% endif %}

${% if values.provision_gce %}
variable "machine_type" {
  type    = string
  default = "${{ values.machine_type }}"
}

variable "boot_disk_type" {
  type    = string
  default = "${{ values.boot_disk_type }}"
}
${% endif %}

${% if values.provision_gcs %}
variable "bucket_suffix" {
  type    = string
  default = "${{ values.bucket_suffix }}"
}

variable "storage_class" {
  type    = string
  default = "${{ values.storage_class }}"
}
${% endif %}

${% if values.provision_cloud_sql %}
variable "db_engine" {
  type    = string
  default = "${{ values.db_engine }}"
}

variable "db_version" {
  type    = string
  default = "${{ values.db_version }}"
}

variable "tier" {
  type    = string
  default = "${{ values.tier }}"
}

variable "availability_type" {
  type    = string
  default = "${{ values.availability_type }}"
}

variable "admin_password" {
  type      = string
  sensitive = true
  # Set via: export TF_VAR_admin_password="your-password"
}
${% endif %}
